//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyectos
    {
        public int IdProyecto { get; set; }
        public string Nombre { get; set; }
        public decimal Importe { get; set; }
        public int IdVendedor { get; set; }
        public int Porcentaje { get; set; }
    
        public virtual Vendedores Vendedores { get; set; }
    }
}
