//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaVentas.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Proyectos
    {
        public int IdProyecto { get; set; }
        public string Nombre { get; set; }
        public decimal Importe { get; set; }
        public int IdVendedor { get; set; }
        public string Porcentaje { get; set; }
        public string Descripcion { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",
               ApplyFormatInEditMode = true)]
        public System.DateTime FechaCreacion { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}",
               ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> FechaCierre { get; set; }
        public string LinkNube { get; set; }
        public string Moneda { get; set; }
        public string Status { get; set; }
        public string Competidores { get; set; }
        public string Observaciones { get; set; }
    
        public virtual Vendedores Vendedores { get; set; }
    }
}
